# dependencies for structural color package
#
# To use:
#   conda env create -f .\environment.yml
# and then
#   conda activate pymie
#
# To update dependencies after changing this environment file:
#   conda env update --name pymie --file environment.yml --prune
#
# can also use mamba instead of conda in the above
name: pymie
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - numpy
  - scipy
  - pandas
  - pint
  - ipython
  - matplotlib
  - seaborn

  # include jupyterlab for convenience
  - jupyterlab

  # for running tests
  - pytest

  # for development
  - pyright
  - pylint
  - flake8
  - autoflake
  - epc
  - isort
  - yapf
  - debugpy
  - pip

  - pip:
      - importmagic
